# parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: './tsconfig.json'
env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'airbnb-typescript/base'
  - 'prettier'
  - 'prettier/@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  '@typescript-eslint/camelcase': off
  'import/prefer-default-export': off
